[global]
disableWidgetStateDuplicationWarning = true

[browser]
gatherUsageStats = false

[client]
caching = false
showErrorDetails = false
toolbarMode = "minimal"

[theme]

# Primary accent color for interactive elements.
primaryColor = "#4A5F2E"

# Background color for the main content area.
backgroundColor = "#0C2C19"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#68705E"

# Color used for almost all text.
textColor = "#FFF"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"
